export type Lang = 'en' | 'th';

export interface T {
  nav: { dashboard: string; loans: string; payments: string; tracking: string; customers: string; users: string; parser: string; audit: string };
  logout: string;
  login: { subtitle: string; email: string; password: string; signIn: string; signingIn: string; defaultCreds: string; loginFailed: string };
  dashboard: { title: string; subtitle: string; totalLoans: string; active: string; totalPrincipal: string; totalCollected: string; payments: string; outstandingBalance: string; pendingPayments: string; awaitingVerification: string; overdueInstallments: string; monthlyCollections: string; noData: string; loanStatusDist: string };
  loans: { title: string; totalFmt: (n: number) => string; newLoan: string; all: string; noFound: string; loading: string; cols: { loanNo: string; customer: string; principal: string; rate: string; term: string; monthly: string; paid: string; status: string }; view: string; edit: string };
  loanDetail: { approve: string; reject: string; principal: string; interestRate: string; term: string; monthlyPayment: string; pa: string; months: string; repaymentProgress: string; startDate: string; purpose: string; notes: string; recordPayment: string; edit: string; documents: string; files: string; addImage: string; uploading: string; noDocs: string; schedule: string; noSchedule: string; schedCols: { no: string; dueDate: string; principal: string; interest: string; amount: string; balance: string; status: string }; loading: string; notFound: string; failed: string };
  editLoan: { title: string; subtitle: string; customer: string; principal: string; interestRate: string; term: string; startDate: string; purpose: string; notes: string; purposePlaceholder: string; notesPlaceholder: string; selectCustomer: string; selectTerm: string; months: string; estimatedPayment: string; totalRepayable: string; cancel: string; save: string; saving: string; failed: string; scheduleWarning: string };
  newLoan: { title: string; subtitle: string; customer: string; principal: string; interestRate: string; perYear: string; perMonth: string; equivAnnual: string; term: string; startDate: string; purpose: string; notes: string; slip: string; purposePlaceholder: string; notesPlaceholder: string; selectCustomer: string; selectTerm: string; months: string; estimatedPayment: string; totalRepayable: string; cancel: string; create: string; creating: string; failed: string; scheduleTable: string; schedCols: { no: string; dueDate: string; principal: string; interest: string; total: string }; schedReset: string; schedTotalInterest: string; schedGrandTotal: string };
  payments: { title: string; totalFmt: (n: number) => string; record: string; noFound: string; loading: string; cols: { loanNo: string; customer: string; term: string; amount: string; date: string; slip: string; status: string }; view: string; verify: string; viewSlip: string };
  newPayment: { title: string; subtitle: string; loan: string; amount: string; date: string; slip: string; notes: string; loadingLoans: string; selectLoan: string; cancel: string; submit: string; submitting: string; selected: string; failed: string };
  paymentDetail: { title: string; loading: string; notFound: string; amount: string; paymentDate: string; submitted: string; verified: string; verifiedBy: string; note: string; rejectReason: string; paymentSlip: string; viewSlipDoc: string; approvePayment: string; rejectPayment: string; processing: string; rejecting: string; rejectReasonLabel: string; rejectPlaceholder: string; cancel: string; confirmReject: string; late: string; failed: string };
  customers: { title: string; totalFmt: (n: number) => string; add: string; search: string; noFound: string; loading: string; cols: { name: string; email: string; joined: string; status: string }; active: string; inactive: string; viewLoans: string };
  users: { title: string; totalFmt: (n: number) => string; new: string; search: string; allRoles: string; noFound: string; loading: string; cols: { name: string; email: string; role: string; joined: string; status: string; actions: string }; active: string; inactive: string; edit: string; deactivate: string; activate: string };
  newUser: { title: string; subtitle: string; name: string; email: string; password: string; role: string; namePlaceholder: string; emailPlaceholder: string; passwordPlaceholder: string; roles: { customer: string; staff: string; admin: string }; cancel: string; create: string; creating: string; failed: string };
  status: { pending: string; active: string; completed: string; defaulted: string; rejected: string; approved: string; paid: string; overdue: string; admin: string; staff: string; customer: string };
}

const en: T = {
  nav: { dashboard: 'Dashboard', loans: 'Loans', payments: 'Payments', tracking: 'Tracking', customers: 'Customers', users: 'Users', parser: 'Parser', audit: 'Medical Audit' },
  logout: 'Logout',
  login: { subtitle: 'Loan Management System', email: 'Email', password: 'Password', signIn: 'Sign in', signingIn: 'Signing in…', defaultCreds: 'Default: admin@loanapp.com / Admin@1234', loginFailed: 'Login failed' },
  dashboard: { title: 'Dashboard', subtitle: 'Loan management overview', totalLoans: 'Total Loans', active: 'active', totalPrincipal: 'Total Principal', totalCollected: 'Total Collected', payments: 'payments', outstandingBalance: 'Outstanding Balance', pendingPayments: 'Pending Payments', awaitingVerification: 'awaiting verification', overdueInstallments: 'Overdue Installments', monthlyCollections: 'Monthly Collections (Last 6 months)', noData: 'No data yet', loanStatusDist: 'Loan Status Distribution' },
  loans: { title: 'Loans', totalFmt: (n) => `${n} total loans`, newLoan: '+ New Loan', all: 'All', noFound: 'No loans found.', loading: 'Loading…', cols: { loanNo: 'Loan #', customer: 'Customer', principal: 'Principal', rate: 'Rate', term: 'Term', monthly: 'Monthly', paid: 'Paid', status: 'Status' }, view: 'View →', edit: 'Edit' },
  loanDetail: { approve: 'Approve', reject: 'Reject', principal: 'Principal', interestRate: 'Interest Rate', term: 'Term', monthlyPayment: 'Monthly Payment', pa: '% p.a.', months: 'months', repaymentProgress: 'Repayment Progress', startDate: 'Start Date', purpose: 'Purpose', notes: 'Notes', recordPayment: '+ Record Payment', edit: 'Edit', documents: 'Documents & Images', files: 'files', addImage: 'Add Image', uploading: 'Uploading…', noDocs: 'No documents yet', schedule: 'Amortization Schedule', noSchedule: 'No schedule available.', schedCols: { no: '#', dueDate: 'Due Date', principal: 'Principal', interest: 'Interest', amount: 'Amount', balance: 'Balance', status: 'Status' }, loading: 'Loading…', notFound: 'Loan not found.', failed: 'Failed' },
  editLoan: { title: 'Edit Loan', subtitle: 'Update loan details and rebuild schedule', customer: 'Customer *', principal: 'Principal (฿) *', interestRate: 'Annual Interest Rate (%) *', term: 'Term (months) *', startDate: 'Start Date *', purpose: 'Purpose', notes: 'Notes', purposePlaceholder: 'e.g. Home renovation, Car purchase…', notesPlaceholder: 'Additional notes…', selectCustomer: 'Select customer…', selectTerm: 'Select term…', months: 'months', estimatedPayment: 'Estimated Monthly Payment', totalRepayable: 'Total repayable', cancel: 'Cancel', save: 'Save Changes', saving: 'Saving…', failed: 'Failed to update loan', scheduleWarning: 'Changing financial details will rebuild the payment schedule.' },
  newLoan: { title: 'New Loan', subtitle: 'Create a new loan application', customer: 'Customer *', principal: 'Principal (฿) *', interestRate: 'Interest Rate (%) *', perYear: 'Per Year', perMonth: 'Per Month', equivAnnual: 'equiv. annual', term: 'Term (months) *', startDate: 'Start Date *', purpose: 'Purpose', notes: 'Notes', slip: 'Upload Slip (optional)', purposePlaceholder: 'e.g. Home renovation, Car purchase…', notesPlaceholder: 'Additional notes…', selectCustomer: 'Select customer…', selectTerm: 'Select term…', months: 'months', estimatedPayment: 'Estimated Monthly Payment', totalRepayable: 'Total repayable', cancel: 'Cancel', create: 'Create Loan', creating: 'Creating…', failed: 'Failed to create loan', scheduleTable: 'Monthly Interest Schedule', schedCols: { no: '#', dueDate: 'Due Date', principal: 'Principal', interest: 'Interest (฿)', total: 'Total' }, schedReset: 'Reset', schedTotalInterest: 'Total Interest', schedGrandTotal: 'Grand Total' },
  payments: { title: 'Payments', totalFmt: (n) => `${n} total payments`, record: '+ Record Payment', noFound: 'No payments found.', loading: 'Loading…', cols: { loanNo: 'Loan #', customer: 'Customer', term: 'Term', amount: 'Amount', date: 'Date', slip: 'Slip', status: 'Status' }, view: 'View →', verify: 'Verify', viewSlip: 'View' },
  newPayment: { title: 'Record Payment', subtitle: 'Submit a loan payment with slip', loan: 'Loan *', amount: 'Amount (฿) *', date: 'Payment Date *', slip: 'Payment Slip (optional)', notes: 'Note', loadingLoans: 'Loading…', selectLoan: 'Select loan…', cancel: 'Cancel', submit: 'Submit Payment', submitting: 'Submitting…', selected: 'Selected', failed: 'Failed to record payment' },
  paymentDetail: { title: 'Payment', loading: 'Loading…', notFound: 'Payment not found.', amount: 'Amount', paymentDate: 'Payment Date', submitted: 'Submitted', verified: 'Verified', verifiedBy: 'by', note: 'Note', rejectReason: 'Reject Reason', paymentSlip: 'Payment Slip', viewSlipDoc: 'View Slip Document', approvePayment: 'Approve Payment', rejectPayment: 'Reject Payment', processing: 'Processing…', rejecting: 'Rejecting…', rejectReasonLabel: 'Reject Reason', rejectPlaceholder: 'Reason for rejection…', cancel: 'Cancel', confirmReject: 'Confirm Reject', late: 'Late', failed: 'Failed' },
  customers: { title: 'Customers', totalFmt: (n) => `${n} total customers`, add: '+ Add Customer', search: 'Search by name or email…', noFound: 'No customers found.', loading: 'Loading…', cols: { name: 'Name', email: 'Email', joined: 'Joined', status: 'Status' }, active: 'Active', inactive: 'Inactive', viewLoans: 'View Loans →' },
  users: { title: 'Users', totalFmt: (n) => `${n} total users`, new: '+ New User', search: 'Search by name or email…', allRoles: 'All Roles', noFound: 'No users found.', loading: 'Loading…', cols: { name: 'Name', email: 'Email', role: 'Role', joined: 'Joined', status: 'Status', actions: 'Actions' }, active: 'Active', inactive: 'Inactive', edit: 'Edit', deactivate: 'Deactivate', activate: 'Activate' },
  newUser: { title: 'New User', subtitle: 'Create a new system user', name: 'Full Name *', email: 'Email *', password: 'Password *', role: 'Role *', namePlaceholder: 'John Doe', emailPlaceholder: 'user@example.com', passwordPlaceholder: 'Min 8 characters', roles: { customer: 'Customer', staff: 'Staff', admin: 'Admin' }, cancel: 'Cancel', create: 'Create User', creating: 'Creating…', failed: 'Failed to create user' },
  status: { pending: 'Pending', active: 'Active', completed: 'Completed', defaulted: 'Defaulted', rejected: 'Rejected', approved: 'Approved', paid: 'Paid', overdue: 'Overdue', admin: 'Admin', staff: 'Staff', customer: 'Customer' },
};

const th: T = {
  nav: { dashboard: 'แดชบอร์ด', loans: 'สินเชื่อ', payments: 'การชำระ', tracking: 'ติดตาม', customers: 'ลูกค้า', users: 'ผู้ใช้งาน', parser: 'แยกข้อมูล', audit: 'Medical Audit' },
  logout: 'ออกจากระบบ',
  login: { subtitle: 'ระบบจัดการสินเชื่อ', email: 'อีเมล', password: 'รหัสผ่าน', signIn: 'เข้าสู่ระบบ', signingIn: 'กำลังเข้าสู่ระบบ…', defaultCreds: 'ค่าเริ่มต้น: admin@loanapp.com / Admin@1234', loginFailed: 'เข้าสู่ระบบไม่สำเร็จ' },
  dashboard: { title: 'แดชบอร์ด', subtitle: 'ภาพรวมระบบสินเชื่อ', totalLoans: 'สินเชื่อทั้งหมด', active: 'ใช้งาน', totalPrincipal: 'เงินต้นรวม', totalCollected: 'ยอดเก็บได้รวม', payments: 'รายการ', outstandingBalance: 'ยอดคงค้าง', pendingPayments: 'รอการยืนยัน', awaitingVerification: 'รอตรวจสอบ', overdueInstallments: 'งวดค้างชำระ', monthlyCollections: 'ยอดเก็บรายเดือน (6 เดือนล่าสุด)', noData: 'ยังไม่มีข้อมูล', loanStatusDist: 'การกระจายสถานะสินเชื่อ' },
  loans: { title: 'สินเชื่อ', totalFmt: (n) => `สินเชื่อทั้งหมด ${n} รายการ`, newLoan: '+ สินเชื่อใหม่', all: 'ทั้งหมด', noFound: 'ไม่พบสินเชื่อ', loading: 'กำลังโหลด…', cols: { loanNo: 'เลขที่', customer: 'ลูกค้า', principal: 'เงินต้น', rate: 'ดอกเบี้ย', term: 'ระยะเวลา', monthly: 'รายเดือน', paid: 'ชำระแล้ว', status: 'สถานะ' }, view: 'ดู →', edit: 'แก้ไข' },
  loanDetail: { approve: 'อนุมัติ', reject: 'ปฏิเสธ', principal: 'เงินต้น', interestRate: 'อัตราดอกเบี้ย', term: 'ระยะเวลา', monthlyPayment: 'ผ่อนรายเดือน', pa: '% ต่อปี', months: 'เดือน', repaymentProgress: 'ความคืบหน้าการชำระ', startDate: 'วันเริ่มต้น', purpose: 'วัตถุประสงค์', notes: 'หมายเหตุ', recordPayment: '+ บันทึกการชำระ', edit: 'แก้ไข', documents: 'เอกสาร & รูปภาพ (เงินต้น)', files: 'ไฟล์', addImage: 'เพิ่มรูปภาพ', uploading: 'กำลังอัปโหลด…', noDocs: 'ยังไม่มีเอกสาร', schedule: 'ตารางผ่อนชำระ', noSchedule: 'ยังไม่มีตารางผ่อนชำระ', schedCols: { no: '#', dueDate: 'วันครบกำหนด', principal: 'เงินต้น', interest: 'ดอกเบี้ย', amount: 'ยอดชำระ', balance: 'คงเหลือ', status: 'สถานะ' }, loading: 'กำลังโหลด…', notFound: 'ไม่พบสินเชื่อ', failed: 'เกิดข้อผิดพลาด' },
  editLoan: { title: 'แก้ไขสินเชื่อ', subtitle: 'แก้ไขรายละเอียดและสร้างตารางผ่อนใหม่', customer: 'ลูกค้า *', principal: 'เงินต้น (฿) *', interestRate: 'อัตราดอกเบี้ยต่อปี (%) *', term: 'ระยะเวลา (เดือน) *', startDate: 'วันเริ่มต้น *', purpose: 'วัตถุประสงค์', notes: 'หมายเหตุ', purposePlaceholder: 'เช่น ซื้อบ้าน, ซื้อรถ…', notesPlaceholder: 'หมายเหตุเพิ่มเติม…', selectCustomer: 'เลือกลูกค้า…', selectTerm: 'เลือกระยะเวลา…', months: 'เดือน', estimatedPayment: 'ยอดผ่อนรายเดือน (ประมาณ)', totalRepayable: 'ยอดชำระรวม', cancel: 'ยกเลิก', save: 'บันทึก', saving: 'กำลังบันทึก…', failed: 'แก้ไขสินเชื่อไม่สำเร็จ', scheduleWarning: 'การเปลี่ยนข้อมูลเงินกู้จะสร้างตารางผ่อนชำระใหม่ทั้งหมด' },
  newLoan: { title: 'สร้างสินเชื่อใหม่', subtitle: 'กรอกข้อมูลสินเชื่อ', customer: 'ลูกค้า *', principal: 'เงินต้น (฿) *', interestRate: 'อัตราดอกเบี้ย (%) *', perYear: 'ต่อปี', perMonth: 'ต่อเดือน', equivAnnual: 'เท่ากับต่อปี', term: 'ระยะเวลา (เดือน) *', startDate: 'วันเริ่มต้น *', purpose: 'วัตถุประสงค์', notes: 'หมายเหตุ', slip: 'อัปโหลดสลิป (ไม่บังคับ)', purposePlaceholder: 'เช่น ซื้อบ้าน, ซื้อรถ…', notesPlaceholder: 'หมายเหตุเพิ่มเติม…', selectCustomer: 'เลือกลูกค้า…', selectTerm: 'เลือกระยะเวลา…', months: 'เดือน', estimatedPayment: 'ยอดผ่อนรายเดือน (ประมาณ)', totalRepayable: 'ยอดชำระรวม', cancel: 'ยกเลิก', create: 'สร้างสินเชื่อ', creating: 'กำลังสร้าง…', failed: 'สร้างสินเชื่อไม่สำเร็จ', scheduleTable: 'ตารางดอกเบี้ยรายงวด', schedCols: { no: 'งวด', dueDate: 'วันครบกำหนด', principal: 'เงินต้น/งวด', interest: 'ดอกเบี้ย (฿)', total: 'ยอดรวม' }, schedReset: 'รีเซ็ต', schedTotalInterest: 'รวมดอกเบี้ย', schedGrandTotal: 'รวมทั้งหมด' },
  payments: { title: 'การชำระเงิน', totalFmt: (n) => `รายการชำระทั้งหมด ${n} รายการ`, record: '+ บันทึกการชำระ', noFound: 'ไม่พบรายการชำระ', loading: 'กำลังโหลด…', cols: { loanNo: 'เลขที่สินเชื่อ', customer: 'ลูกค้า', term: 'ระยะเวลา', amount: 'จำนวน', date: 'วันที่', slip: 'สลิป', status: 'สถานะ' }, view: 'ดู →', verify: 'ยืนยัน', viewSlip: 'ดูสลิป' },
  newPayment: { title: 'บันทึกการชำระเงิน', subtitle: 'ส่งหลักฐานการชำระพร้อมสลิป', loan: 'สินเชื่อ *', amount: 'จำนวน (฿) *', date: 'วันที่ชำระ *', slip: 'สลิปการชำระ (ไม่บังคับ)', notes: 'หมายเหตุ', loadingLoans: 'กำลังโหลด…', selectLoan: 'เลือกสินเชื่อ…', cancel: 'ยกเลิก', submit: 'ยืนยันการชำระ', submitting: 'กำลังส่ง…', selected: 'เลือกแล้ว', failed: 'บันทึกการชำระไม่สำเร็จ' },
  paymentDetail: { title: 'รายละเอียดการชำระ', loading: 'กำลังโหลด…', notFound: 'ไม่พบรายการชำระ', amount: 'จำนวน', paymentDate: 'วันที่ชำระ', submitted: 'วันที่ส่ง', verified: 'ยืนยันเมื่อ', verifiedBy: 'โดย', note: 'หมายเหตุ', rejectReason: 'เหตุผลที่ปฏิเสธ', paymentSlip: 'สลิปการชำระ', viewSlipDoc: 'ดูเอกสารสลิป', approvePayment: 'อนุมัติการชำระ', rejectPayment: 'ปฏิเสธการชำระ', processing: 'กำลังดำเนินการ…', rejecting: 'กำลังปฏิเสธ…', rejectReasonLabel: 'เหตุผลที่ปฏิเสธ', rejectPlaceholder: 'ระบุเหตุผล…', cancel: 'ยกเลิก', confirmReject: 'ยืนยันการปฏิเสธ', late: 'ล่าช้า', failed: 'เกิดข้อผิดพลาด' },
  customers: { title: 'ลูกค้า', totalFmt: (n) => `ลูกค้าทั้งหมด ${n} ราย`, add: '+ เพิ่มลูกค้า', search: 'ค้นหาชื่อหรืออีเมล…', noFound: 'ไม่พบลูกค้า', loading: 'กำลังโหลด…', cols: { name: 'ชื่อ', email: 'อีเมล', joined: 'วันที่สมัคร', status: 'สถานะ' }, active: 'ใช้งาน', inactive: 'ปิดใช้งาน', viewLoans: 'ดูสินเชื่อ →' },
  users: { title: 'ผู้ใช้งาน', totalFmt: (n) => `ผู้ใช้งานทั้งหมด ${n} คน`, new: '+ ผู้ใช้งานใหม่', search: 'ค้นหาชื่อหรืออีเมล…', allRoles: 'ทุกบทบาท', noFound: 'ไม่พบผู้ใช้งาน', loading: 'กำลังโหลด…', cols: { name: 'ชื่อ', email: 'อีเมล', role: 'บทบาท', joined: 'วันที่สมัคร', status: 'สถานะ', actions: 'จัดการ' }, active: 'ใช้งาน', inactive: 'ปิดใช้งาน', edit: 'แก้ไข', deactivate: 'ปิดการใช้งาน', activate: 'เปิดการใช้งาน' },
  newUser: { title: 'ผู้ใช้งานใหม่', subtitle: 'สร้างบัญชีผู้ใช้งานในระบบ', name: 'ชื่อ-นามสกุล *', email: 'อีเมล *', password: 'รหัสผ่าน *', role: 'บทบาท *', namePlaceholder: 'ชื่อ นามสกุล', emailPlaceholder: 'user@example.com', passwordPlaceholder: 'อย่างน้อย 8 ตัวอักษร', roles: { customer: 'ลูกค้า', staff: 'เจ้าหน้าที่', admin: 'แอดมิน' }, cancel: 'ยกเลิก', create: 'สร้างผู้ใช้งาน', creating: 'กำลังสร้าง…', failed: 'สร้างผู้ใช้งานไม่สำเร็จ' },
  status: { pending: 'รอจ่ายตามกำหนด', active: 'ใช้งาน', completed: 'เสร็จสิ้น', defaulted: 'ผิดนัด', rejected: 'ปฏิเสธ', approved: 'อนุมัติ', paid: 'ชำระแล้ว', overdue: 'เกินกำหนด', admin: 'แอดมิน', staff: 'เจ้าหน้าที่', customer: 'ลูกค้า' },
};

export const translations: Record<Lang, T> = { en, th };
